Projetos Django/Projeto 2/mysite/animals/urls.py
from django.urls import path

from . import views
app_name = "animals"
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:animal_id>/', views.animaldetail,name='detail'),
    path('habitats/<int:habitat_id>/', views.habitatview,name='habitat'),
    path('<int:animal_id>/vote/', views.voteanimal,name='vote'),
]

Projetos Django/Projeto 2/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('animals/', include('animals.urls')),
    path("admin/", admin.site.urls)
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Projetos Django/Projeto 2/mysite/animals/models.py
from django.db import models

# Create your models here.
class habitat(models.Model):
    Region_Name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000,default="Nenhuma descrição foi adicionada")
    

    def __str__(self):
        return self.Region_Name

class animal(models.Model):
    specie_name = models.CharField(max_length=200)
    habitat = models.ForeignKey(habitat, on_delete=models.CASCADE, default=1)
    animal_image = models.ImageField(upload_to="images")
    votes = models.IntegerField(default=0)
    Animal_description = models.CharField(max_length=1000, default="")
    def __str__(self):
        return self.specie_name
    
    

Projetos Django/Projeto 2/mysite/animals/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import animal,habitat
# Create your views here.


def index(request):
    a_animals = animal.objects.all()
    a_habitats = habitat.objects.all()
    package = {'a_animals': a_animals, 'a_habitats': a_habitats}
    return render(request,"index.html",package)

def animaldetail(request, animal_id):
    anim = get_object_or_404(animal,pk=animal_id)
    animals = animal.objects.all()

    total_votes = 0
    for a in animals:
        total_votes += a.votes

    context = {'anim': anim, 'total_votes': total_votes} 
    return render(request,"detail.html",context)

def habitatview(request, habitat_id):
    habit = get_object_or_404(habitat,pk=habitat_id)
    context = {'habitat': habit} 
    return render(request,"habitat.html",context)

def voteanimal(request, animal_id):
    anim = get_object_or_404(animal,pk=animal_id)
    anim.votes += 1
    anim.save()
    return HttpResponseRedirect(reverse('animals:detail',args=[anim.id]))
    

Projetos Django/Projeto 2/mysite/animals/templates/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{anim.specie_name}} details</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: open sans, Arial, Tahoma, Verdana, sans-serif;
        }

        header {
            background-color: rgb(204, 255, 137);
            display: flex;
            justify-content: center;
            height: 60px;
        }

        .title {
            margin: 10px;
        }

        main {
            background-color: lightgray;
            margin: 0px 100px 0px 100px;
            display: flex;
            height: 700px;
            padding: 200px;
        }

        .description{
            margin: 10px ;
            font-size: 20px
        }
        .Button{
            position: absolute;
            bottom: 80px;
            height: 50px;
            width: 100px;
        }
        .votes_bar{
            background-color: lightcoral;
            position: absolute;
            width: 30%;
            bottom: 80px;
            height: 50px;
            display: flex;

        }
    </style>
</head>

<body>
    <header>
        <h1 class="title"> Animal: {{anim.specie_name}}</h1>
    </header>
    <main>
        <img src="{{anim.animal_image.url}}" alt="Legenda">
        <div class="description">
            <p >{{anim.Animal_description}}</p> <br>
            Habitat:<a href="{% url 'animals:habitat' anim.habitat.id %}">{{ anim.habitat.Region_Name}}</a>

        </div>
        <form action="{% url 'animals:vote' anim.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Vote" class="Button">

        </form>
        <div class="votes_bar"> <p style="text-align: center;">{{ total_votes }} / {{anim.votes }}</p></div>

    </main>

</body>

</html>
<!--

-->

Projetos Django/Projeto 2/mysite/animals/templates/habitat.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Habitat</title>
</head>
<body>
    eeeeee
</body>
</html>

Projetos Django/Projeto 2/mysite/animals/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
        font-family: open sans, Arial, Tahoma, Verdana, sans-serif;
    }
    header{
        background-color: rgb(204, 255, 137);
        display: flex;
        justify-content: center;
        height: 60px;
    }
    .title{
        margin: 10px;
    }
    main{
        background-color: lightgray;
        margin: 0px 100px 0px 100px;
        display: flex;
        height: 700px;
        padding: 200px;
    }
    .animal{
        background-color: aquamarine;
        margin: 2%;
        height: 200px;
    }
    </style>
</head>
<body>
    <header>
        <h1 class="title"> Choose the cutest </h1>
    </header>
    <main>
        {% for anim in a_animals %} 
        <a class="animal" href="{% url 'detail' anim.id %}">
            <p> {{ anim.specie_name }}</p>
            <img src="{{ anim.animal_image.url }}" alt="{{ anim.specie_name }} + ' image'" height="90%">
        </a>
        {% endfor %}

    </main>
</body>
</html>
<!--

-->